server:
  port: 9999
  servlet:
    context-path: /pay

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/j2ee?useSSL=false
    username: root
    password: "000000"
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

